# Generated by Django 5.2.3 on 2025-06-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icon', models.URLField(blank=True, null=True)),
                ('sign', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
