# Generated by Django 5.2.3 on 2025-06-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wachemosaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('reporter', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('day', models.FloatField(max_length=2)),
                ('month', models.CharField(max_length=4)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='features',
        ),
    ]
