# Generated by Django 5.2.3 on 2025-06-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wachemosaps', '0002_news_delete_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='imageurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
