# Generated by Django 5.2.3 on 2025-06-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wachemosaps', '0005_alter_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='imageurl',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
