# Generated by Django 5.2.3 on 2025-06-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wachemosaps', '0008_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
