# Generated by Django 5.2.7 on 2026-10-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wachemosaps', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
