# Generated by Django 5.2.7 on 2026-10-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wachemosaps', '0014_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=10),
        ),
    ]
